### ISSUE TITLE
Error: Unable to dynamically load

### ISSUE THREAD

**Issue by g2mXagent** [asaf-b/mnsAnnotate#1]
Win10
Maya 2020.2

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/Users/[USER NAME]/Documents/maya/2020/plug-ins/mnsAnnotate.mll
The specified module could not be found.

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: The specified module could not be found.
 (mnsAnnotate) //

**Comment by asaf-b** [comment]
Hi g2mXagent,
Are you sure you are using the plugin MLL file from the provided win/2020 folder?
Because that loads just fine in my Maya 2020.2 version (also win10).
Can I kindly ask you to make sure you load the plugin from the current build folder please - .../mnsAnnotate/win/2020 
I attached my test below:
![mnsAnnotata2020-2](https://user-images.githubusercontent.com/30810818/90519526-cf604100-e170-11ea-8d0f-6322b2f75c8b.jpg)

Please keep me updated or if there is anything else I can help with.
Asaf Ben Zur

**Comment by asaf-b** [comment]
Hi again,
Since you didn't provide any information with this error, I can also assume another scenario this error will occur :
If you load the plugin, then choose to "auto-load" it without adding the plug-in into your PLUGIN_PATH, when you start-up Maya this error will occur (just like with any manually loaded plugin).

If you want to "auto-load" the plugin, place the necessary MLL file within any directory, and add that directory into your `Maya.env` file using MAYA_PLUGIN_PATH environment variable.
In case you load the plugin manually and choose to "auto-load" it- when Maya is initialized it will try to locate the plugin but will fail to do so since it doesn't know where it is- and this error will be written into the command history log.

Best,
Asaf Ben Zur

**Comment by g2mXagent** [comment]
Today I successfully loaded the plug-in, I don't know why.
but there is no "Attributes" let me plug in.
https://imgur.com/PggfT89

**Comment by asaf-b** [comment]
good to hear.
It's hidden, use the connections editor/code to connect the first attribute.
Closing this. 

Asaf Ben Zur
